### ISSUE TITLE
Required design for user to follow

### ISSUE THREAD

**Issue by Sword-Smith** [HIPERFIT/hipermark#1]
This is the temporary specification of the design that the user must follow in order for hipermark to work. 

Hipermark should be called from the root directory of the structure presented in "Data Structure" in README.md. Besides from the directory structure, the user must provide these files:
instantiate, instantiate_data, and Makefile
#### instantiate

An executable that follows these principles:
- These arguments are available within the program since the program is executed with these environment variables. The paths are specified relative to the root folder described above.
  - HIPERMARK_LIB_DIR -- /lib
  - HIPERMARK_BENCHMARK_LIB_DIR -- /benchmarks/<benchmark>/implementations/<implementation>/lib
  - HIPERMARK_IMPLEMENTATION -- /benchmarks/<benchmark>/implementations/<implementation>
  - HIPERMARK_PLATFORM --
- Copy all required files from source destination to instantiate destination. The instantiate destination is the current folder ("./") since hipermark will start a process in which the \
  program is executed and this process' path will be the place to store the binary of the source code of the implementation.
- The /lib/generate_platform_mk.py Python script must be executed with the argument of the desired platform and the output must be placed in ./platform.mk (relative to the folder of t\
  he execution of "instantiate". Relatively to the root directory of the benchmark, the same path is: /instantiations/"<benchmark>-<implementation>"/).
- A run executable which can take an argument and pipe this argument into the executable must be generated by the execution of the instantiate program.
- The user (in the OS sense) creating the "run" must be able to execute "run". "run" is also placed in the folder ./ compared to the execution of instantiate.

**Comment by athas** [comment]
Thorkil Værge notifications@github.com writes:

> Hipermark should be called from the root directory of the structure presented in "Data Structure" below. Besides from the directory structure, the user must provide these files:
> instantiate, instantiate_data, and Makefile

`Makefile` does not seem necessary if you require `instantiate` and
`instantiate_data`.  Eventually, however, we should just require a
single `Makefile` with different targets.

> - HIPERMARK_BENCHMARK_LIB_DIR -- /benchmarks/<benchmark>/implementations/<implementation>/lib

Should this not be `/benchmarks/<benchmark>/lib`?  After all,
`/benchmarks/<benchmark>/implementations/<implementation>/lib` can
always be written `$HIPERMARK_IMPLEMENTATION/lib` anyway.

> - HIPERMARK_PLATFORM --

Don't worry about this one for now.  Eventually, it should probably be
`HIPERMARK_COMPILE_TIME_CONFIGURATION` or something like that.

> - The /lib/generate_platform_mk.py Python script must be executed
>   with the argument of the desired platform and the output must be
>   placed in ./platform.mk (relative to the folder of t\ he execution of
>   "instantiate". Relatively to the root directory of the benchmark, the
>   same path is: /instantiations/"<benchmark>-<implementation>"/).

This is a specific quirk/implementation strategy of the C-based
benchmark implementations.  Neither the Haskell or Futhark
implementations will (probably) make use of an .mk file.  The important
thing is that the chosen configuration is reflected in the build.

> - A run executable which can take an argument and pipe this argument
>   into the executable must be generated by the execution of the
>   instantiate program.

What does it mean to "pipe this argument"?  Also, you rae
overspecifying: `instantiate` does not necessary create an executable,
for example if the implementation is written in an interpreted language
like Python.  The important thing is that `run` _works_, it does not
matter exactly how it does it.

## 

\  Troels
/\ Henriksen
