### ISSUE TITLE
Hiperpret should be able to export data to a file

### ISSUE THREAD

**Issue by Sword-Smith** [HIPERFIT/hipermark#10]
Using hiperpret to visualize output is nice and dandy but it seems extremely likely that some users would want to export data of the run times and other results that hiperpret has read from the output of hipermark.

The best way to think of the entire dataset that hipermark produces is as a multidimensional array. One dimension for benchmarks, one for implementations, one for each compile-time variable, one for datasets, one for each run-time variable, and one for each run. The values of the multidimensional array are, in the general case, arrays themselves since both runtime, two timestamps and other outputs are produced for each run. What is the best way of representing this data so that it can be imported into other programs like MatLab or Excel? The only format that I would know how to handle this way is JSON -- and a toolbox for handling JSON in MatLab does exist.

So it would seem like a very reasonable functional requirement that hiperpret should be able to export all output data as a JSON file.

**Comment by athas** [comment]
Export JSON or CSV - these are both extremely widespread formats.

**Comment by Sword-Smith** [comment]
Hipermark can now both export a list of dicts describing the runs and a list of the dicts describing each configuration an implementation has been run with. The latter obviously includes average runtimes over the runs, standard deviations of this , and uncertainties of the averages.
