### ISSUE TITLE
How should hipermark handle overwriting of output files?

### ISSUE THREAD

**Issue by Sword-Smith** [HIPERFIT/hipermark#2]
hipermark produces output files in the folder instantiations/<benchmark>-<implementation>/run_output/<dataset>/<run_number_counter>/

When the program is run again, then the output files for the new run overwrites the old files. But if the implementation fails to execute, then only some files are overwritten and other remain unchanged and represent output data from a previous execution. This might introduce confusion or mistakes. Is it the user's responsibility to manage these potential pitfalls or should I code something clever?

I guess if the folder in which the output files should be saved is specified as a command line argument by the user, then the problem is ameliorated but the user could choose to specify a folder which already contained output data and the same problem would occur.

Did we come up with a answer to where the output files should be placed?

**Comment by athas** [comment]
Thorkil Værge notifications@github.com writes:

> I guess if the folder in which the output files should be saved is
> specified as a command line argument by the user, then the problem is
> ameliorated but the user could choose to specify a folder which
> already contained output data and the same problem would occur.

If file name conflicts occur (i.e. if a folder of the name already
exists), then exit with an error.  During development, this is would be
annoying, so don't implement this yet.  In the long run, I don't think
we should always use the 'instantiations' folder, but instead a unique
name per what Cosmin calls a "transaction".

> Did we come up with a answer to where the output files should be
> placed?

No.  This is something we need to explore in detail once we have a
better idea of the full picture.

## 

\  Troels
/\ Henriksen
