### ISSUE TITLE
Is the hiperpret datastructure sensible?

### ISSUE THREAD

**Issue by Sword-Smith** [HIPERFIT/hipermark#3]
The current hiperfit program hiperpret can interpret the results that hipermark creates. It is currently quite strict in that the program throws an uncaught exception if the correct files and folders are not present. The folder that the program looks in is given as argument when the program is launched. E.g.: "./hiperpret instantiations/".

I thought it was sensible to use classes to structure the program: benchmark->implementation->case->run.
For now, I have used lists within the objects to handle the sub objects, meaning that the different implementations in a benchmark b are accessed as "b.implementations[n]", where n is an integer.

Is it better to use dicts for this such that an implementation is accessed by: 
"b.implementations['cpp_openmp']" or are lists ok?

I wanted to check if the program made sense before advancing further.

**Comment by athas** [comment]
Thorkil Værge notifications@github.com writes:

> The current hiperfit program can interpret the results that hipermark
> creates. It is currently quite strict in that the program throws an
> uncaught exception if the correct files and folders are not
> present.

Good for now, but eventually it might be useful to add an exception
handler that can give a more understandable error message to the user.

> For now, I have used lists within the objects to handle the sub
> objects, meaning that the different implementations in a benchmark b
> are accessed as "b.implementations[n]", where n is an integer.
> 
> Is it better to use dicts for this such that an implementation is accessed by: 
> "b.implementations['cpp_openmp']" or are lists ok?

Please use dictionaries indexed by the benchmark name instead.

## 

\  Troels
/\ Henriksen
