### ISSUE TITLE
Runtime and compile-time configuration

### ISSUE THREAD

**Issue by athas** [HIPERFIT/hipermark#4]
I will soon put a suggestion for configuration design here.  To guide the design, I will assume we will want to support at least the following (not every implementation will need all of these):
- Runtime configuration:
  - Number of CPU threads
  - OpenCL platform and device
- Compile-time configuration:
  - Whether to use single- or double-precision.
  - Various other boolean flags that in C translate to preprocessor symbols.

These should not be baked into the configuration language, but the language should be powerful enough to support them.  I will try to think of some JSON-based encoding scheme (proper JSON schemas are likely too heavyweight).

**Comment by Sword-Smith** [comment]
Is this issue considered solved?

**Comment by Sword-Smith** [comment]
I am closing this issue since I consider it solved.
