### ISSUE TITLE
Status of todays work

### ISSUE THREAD

**Issue by Sword-Smith** [HIPERFIT/hipermark#5]
The validation function program has been written and hipermark can look for it, start it, and interpret its result. I have made some decisions and I would like to receive feedback if necessary.

Today I have ported the validation function for InterestCalib from C++ into a Python script which is located in the new-design-Thor branch of the finpar repository. It is located at benchmarks/<benchmark>/lib/include/validation_function which is also the only place where hipermark looks for an external validation file.

Hipermark has been fixed to look for an external validation file and start a new sub process for this program if any is found. The files which are compared in the external validation program, a result output and an expected output, are passed to the function as arguments such that the validation program must read the arguments which the OS passes to it, just like if an argument is passed to a program through the command line. The file names, and not JSON objects, are passed to the validation function. So it is the responsibility of the validation function to read and parse the JSON files it receives as arguments.

The validation program uses the return code to communicate the result of the comparison to the hipermark program. 0 means succes and 1 means failure. The validation.txt stores the (XOR 1) of the returncode meaning that validation.txt contains "1\n" if the validation succeeds.

The output of standard error and standard out of the process running the validation_function is stored as files in the run_output folder under instantiations.

The output generated by hipermark running InterestCalib/CppOpenMP has also been parsed succesfully by hiperpret.

**Comment by athas** [comment]
Thorkil Værge notifications@github.com writes:

> The validation function program has been written and hipermark can
> look for it, start it, and interpret its result. I have made some
> decisions and I would like to receive feedback if necessary.
> 
> Today I have ported the validation function for InterestCalib from C++
> into a Python script which is located in the new-design-Thor branch of
> the finpar repository. It is located at
> benchmarks/<benchmark>/lib/include/validation_function which is also
> the only place where hipermark looks for an external validation file.

I don't like this path - it is too hidden.  Besides, lib/include is
supposed to be for C header files, and lib is for random crap that might
be useful to multiple implementations.  Put the validation program in
benchmarks/<benchmark>/validation_function directly.

> Hipermark has been fixed to look for an external validation file and
> start a new sub process for this program if any is found. The files
> which are compared in the external validation program, a result output
> and an expected output, are passed to the function as arguments such
> that the validation program must read the arguments which the OS
> passes to it, just like if an argument is passed to a program through
> the command line. The file names, and not JSON objects, are passed to
> the validation function. So it is the responsibility of the validation
> function to read and parse the JSON files it receives as arguments.

This is the correct design (although in principle there is no
requirement that the files contain JSON).

> The validation program uses the return code to communicate the result
> of the comparison to the hipermark program. 0 means succes and 1 means
> failure. The validation.txt stores the (XOR 1) of the returncode
> meaning that validation.txt contains "1\n" if the validation succeeds.
> 
> The output of standard error and standard out of the process running
> the validation_function is stored as files in the run_output folder
> under instantiations.
> 
> The output generated by hipermark running InterestCalib/CppOpenMP has
> also been parsed succesfully by hiperpret.

Good work!

## 

\  Troels
/\ Henriksen

**Comment by Sword-Smith** [comment]
The path where hipermark has been changed to /benchmarks/<benchmark>/validation_function.

The HIPERMARK_RESULT environment variable which is set when spawning a sub process is defined as "result.json". Is that problematic?

**Comment by athas** [comment]
Thorkil Værge notifications@github.com writes:

> The HIPERMARK_RESULT environment variable which is set when spawning a sub process is defined as "result.json". Is that problematic?

No; it it easy to change this later.  There is an important design
principle at play here:

https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

Basically, we don't need to implement the specifics of features we don't
need yet, as long as we don't overspecify so much that we cannot
implement them at all in the future.

## 

\  Troels
/\ Henriksen
