### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by Sword-Smith** [HIPERFIT/hipermark#6]
There are a lot of different kinds of tests in software engineering and I haven't used too many of them.

Obviously, I test the programs that I writing by simply running them on some basic/standard input files/file systems. But there is no rigorous testing of the functions and programs that I am writing. Should there be?

**Comment by athas** [comment]
Thorkil Værge notifications@github.com writes:

> There are a lot of different kinds of tests in software engineering and I haven't used too many of them.
> 
> Obviously, I test the programs that I writing by simply running them
> on some basic/standard input files/file systems. But there is no
> rigorous testing of the functions and programs that I am
> writing. Should there be?

Ideally, but let's not worry yet.  Hipermark is simple enough that the
testable things are easy to get right, and the complex things are a
nightmare to test.

## 

\  Troels
/\ Henriksen

**Comment by Sword-Smith** [comment]
Actually, hiperpret tests the files and folders that hipermark creates in a very rigorous way so this aspect of hipermark testing is accounted for.
