### ISSUE TITLE
Proper command line parser

### ISSUE THREAD

**Issue by athas** [HIPERFIT/hipermark#9]
Instead of the current ad-hoc system of positional options, use a proper command line parser and implement options `--benchmark`, `--implementation`, `--dataset`, `--run-iterations`, `--instantiation-directory`, and whatever else we find appropriate.

**Comment by Sword-Smith** [comment]
This is fixed for Hiperpret but not yet for Hipermark.

**Comment by Sword-Smith** [comment]
Now also fixed for HIPERmark
